config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :products do
    get :who_brought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store_index', via: :all
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Depot</title>
    <%= csrf_meta_tags %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <body class='<%= controller.controller_name %>'>
      <div id="banner">
        <%= form_tag store_index_path, class: 'locale' do %>
          <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()' %>
          <%= submit_tag 'submit' %>
          <%= javascript_tag "$('.locale input').hide()" %>
        <% end %>
      <title>Depot</title>
      <%= csrf_meta_tags %>
      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <span class="title"><%= @page_title %></span>
      </div>
      <div id="columns">
        <div id="side">
          <div id="cart">
            <% if @cart %>
              <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
                <%= render @cart %>
              <% end %>
            <% end %>
          </div>
          <ul>
            <li><a href="/"><%= t('.home') %></a></li>
            <li><a href="http://www..../faq"><%= t('.questions') %></a></li>
            <li><a href="http://www..../news"><%= t('.news') %></a></li>
            <li><a href="http://www..../contact"><%= t('.contact') %></a></li>
          </ul>
        </div>


        <% if session[:user_id] %>
          <ul>
            <li><%= link_to 'Orders', orders_path %></li>
            <li><%= link_to 'Products', products_path %></li>
            <li><%= link_to 'Users', users_path %></li>
          </ul>
          <%= button_to 'Logout', logout_path, method: :delete %>
        <% end %>

        <div id="main">
          <%= yield %>
        </div>
      </div>
  </body>
</html>